#ifndef K_SYS_DEFS_H
#define K_SYS_DEFS_H

#include <stdint.h>

#define K_SYS_SYSCALL_VECTOR 69
#define K_SYS_SYSCALL_MAX_ARGS 8

/* sizeof(uint32_t) * 8 == 32 */
struct k_sys_syscall_args_t
{
    uint32_t args[K_SYS_SYSCALL_MAX_ARGS];
};

enum result_t
{
    RESULT_OK = 0,
    
    RESULT_INVALID_THREAD,
    RESULT_DETACHED_THREAD,
    
    RESULT_SPINLOCK_ALREADY_LOCKED,
    RESULT_SPINLOCK_ALREADY_UNLOCKED,
    
    RESULT_INVALID_STREAM,
    RESULT_EMPTY_STREAM,
    RESULT_BLOCKED_STREAM,
    
    // RESULT_NOT_ENOUGH_SPACE,
    RESULT_BAD_PARAM,
    RESULT_OUT_OF_RANGE,
    RESULT_OUT_OF_SPACE,
    RESULT_INVALID_DATA,
    RESULT_INCOMPLETE,
    
    
    RESULT_FORBIDDEN,
    RESULT_LINEAR_ADDRESS_IN_USE,
    RESULT_LINEAR_ADDRESS_NOT_IN_USE,
    RESULT_PHYSICAL_PAGE_IN_USE,
    RESULT_PHYSICAL_PAGE_NOT_IN_USE,
    RESULT_PHYSICAL_PAGE_EXCLUSIVE,
    RESULT_OUT_OF_PHYSICAL_MEM,
    RESULT_OUT_OF_VIRTUAL_MEM,
};

#endif